events {}

http {
    upstream myapp {
        # Docker DNS otomatis menerjemahkan nama ini menjadi IP container
        server container-web1:80;
        server container-web2:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://myapp;
        }
    }
}