events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;
        server_name localhost;

        # Jalur 1: Jika user mengakses web biasa (/), arahkan ke file HTML dashboard
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Jalur 2: Jika user submit form (/api), REVERSE PROXY lemparkan ke Express.js (10.10.10.30)
        location /api/ {
            proxy_pass http://10.10.10.30:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
}